[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
healthcheckInterval = 60
healthcheckGracePeriod = 300
healthcheckRetries = 5
startTimeout = 300
restartPolicyMaxRetries = 5 